name: Maven Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write   # ✅ allow pushing to gh-pages branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build and run tests
      - name: Build with Maven
        run: mvn -B clean test

      # Step 4: Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # Step 5: Generate Allure HTML Report
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o reports/allure-report

      # Step 6: Copy Extent Report to reports folder
      - name: Copy Extent Report
        run: mkdir -p reports/extent-report && cp target/extent-report.html reports/extent-report/index.html

      # Step 7: Deploy both reports to GitHub Pages
      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports