name: Maven Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build and run tests
      - name: Build with Maven
        run: mvn -B clean test

      # Step 4: Upload Extent Report
      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: target/extent-report.html

      # Step 5: Install Allure CLI
      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      # Step 6: Generate Allure HTML Report
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      # Step 7: Upload Allure HTML Report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
